apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cbperf-pv-claim
spec:
  storageClassName: trident-ontap-nas
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cbperf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cbperf
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 25%
       maxSurge: 1
  template:
    metadata:
      labels:
        app: cbperf
    spec:
      containers:
      - name: cbperf-container
        image: mminichino/cbperf:latest
        imagePullPolicy: Always
        command: ["/bench/bin/persist.sh"]
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 1001
        volumeMounts:
        - name: data
          mountPath: /data
          readOnly: false
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: cbperf-pv-claim
